# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixMaxCy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MixMaxCy
	

   pod 'Alamofire'
   pod 'Kingfisher'
   pod 'SwiftyJSON'
   pod 'RxSwift', '~> 5'
   pod 'RxCocoa', '~> 5'
   pod 'RealReachability'
   pod 'lottie-ios'
	#SnapKit layout 
   pod 'SnapKit', '4.2.0'
   pod 'CHIPageControl/Aleppo'
   pod 'NVActivityIndicatorView'
  target 'MixMaxCyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MixMaxCyUITests' do
    # Pods for testing
  end

end
